name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "7f5dc37eb4b743618ed87489363b9091"				#KV数据库id
